# Generated by Django 4.0.1 on 2022-02-19 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_remove_choice_question_delete_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
